baseURL = 'https://denhafiz69.github.io/'
languageCode = 'en-us'
title = 'Den Hafiz Portfolio'
theme = 'PaperMod'

publishDir = 'docs'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 20
  
  [[menu.main]]
    name = "Blog"
    url = "/blog/"  # or "/posts/"
    weight = 30

  [[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 40

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 50
